apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-1
  labels:
    app: mysql-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-1
  template:
    metadata:
      labels:
        app: mysql-1
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          ports:
            - containerPort: 3306
              name: mysql-1
          volumeMounts:
            - name: mysql-persistent-storage-1
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage-1
          persistentVolumeClaim:
            claimName: mysql-volumeclaim-1
