apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-lb
  name: nginx-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-lb
