apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress-2
  name: wordpress-2
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress-2
